### ISSUE TITLE
动态线程调整相关

### ISSUE THREAD

**Issue by zephyrize** [CodingHanYa/workspace#38]
线程池支持自动扩容和收缩吗？ 

设置一个最小线程数量和最大线程数量，请求多的时候自动扩容（但小于最大线程数量），请求少的时候可以释放掉多余资源（但不能过度优化，至少保留最少线程数量）

不知道这个框架支不支持扩展这个功能？

**Comment by CodingHanYa** [comment]
参见supervisor
