### ISSUE TITLE
msvc不遵守__cplusplus引起错误

### ISSUE THREAD

**Issue by Side-Cloud** [CodingHanYa/workspace#41]
你的utility.h中，用判断`__cplusplus>=201703L`来决定是否使用invoke_result_t，但在msvc中，__cplusplus始终为199711L，应对各平台使用宏定义来定义通用的c++版本，如下图
![image](https://github.com/CodingHanYa/workspace/assets/160902958/de435c46-9aca-492a-bd4d-590db267fb94)
![image](https://github.com/CodingHanYa/workspace/assets/160902958/81713bfe-4c74-4449-a49a-99d286c30079)

**Comment by CodingHanYa** [comment]
已修复
